class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'appName': {'en': 'Smart Parking', 'ar': 'الباركينج الذكي'},
    'parkingGarage': {'en': 'Parking Garage', 'ar': 'جراج السيارات'},
    'myParking': {'en': 'My Parking', 'ar': 'موقفي'},
    'login': {'en': 'Log In', 'ar': 'تسجيل الدخول'},
    'signup': {'en': 'Sign Up', 'ar': 'إنشاء حساب'},
    'logout': {'en': 'Logout', 'ar': 'تسجيل الخروج'},
    'username': {'en': 'Username', 'ar': 'اسم المستخدم'},
    'password': {'en': 'Password', 'ar': 'كلمة المرور'},
    'email': {'en': 'Email', 'ar': 'البريد الإلكتروني'},
    'firstName': {'en': 'First Name', 'ar': 'الاسم الأول'},
    'lastName': {'en': 'Last Name', 'ar': 'الاسم الأخير'},
    'welcomeBack': {'en': 'Welcome back', 'ar': 'مرحباً بعودتك'},
    'loginSubtitle': {'en': 'Log in to continue booking your parking.', 'ar': 'سجل دخولك لمتابعة حجز موقفك.'},
    'noAccount': {'en': "Don't have an account? Sign up", 'ar': 'ليس لديك حساب؟ سجل الآن'},
    'haveAccount': {'en': 'Already have an account? Log in', 'ar': 'لديك حساب بالفعل؟ سجل دخولك'},
    'createAccount': {'en': 'Create Account', 'ar': 'إنشاء حساب'},
    'welcomeToParking': {'en': 'Welcome to Parking', 'ar': 'مرحباً بك في الباركينج'},
    'createAccountSubtitle': {'en': 'Create an account to book your parking slots.', 'ar': 'أنشئ حساباً لحجز أماكن ركنك.'},
    'confirmPassword': {'en': 'Confirm password', 'ar': 'تأكيد كلمة المرور'},
    'selectParking': {'en': 'Select Parking', 'ar': 'اختر موقف'},
    'confirmBooking': {'en': 'Confirm Booking', 'ar': 'تأكيد الحجز'},
    'selectSlot': {'en': 'Select a Slot', 'ar': 'اختر مكان'},
    'entrance': {'en': 'ENTRANCE', 'ar': 'المدخل'},
    'exit': {'en': 'EXIT', 'ar': 'المخرج'},
    'level': {'en': 'Level', 'ar': 'الطابق'},
    'noSlotsAvailable': {'en': 'No slots available', 'ar': 'لا توجد أماكن متاحة'},
    'activeReservation': {'en': 'You have an active reservation', 'ar': 'لديك حجز نشط'},
    'timeRemaining': {'en': 'TIME REMAINING', 'ar': 'الوقت المتبقي'},
    'expiringSoon': {'en': 'Expiring soon!', 'ar': 'ينتهي قريباً!'},
    'navigateToSlot': {'en': 'Navigate to Slot', 'ar': 'الملاحة للمكان'},
    'cancelReservation': {'en': 'Cancel Reservation', 'ar': 'إلغاء الحجز'},
    'extendReservation': {'en': 'Extend Reservation', 'ar': 'تمديد الحجز'},
    'slot': {'en': 'Slot', 'ar': 'المكان'},
    'floor': {'en': 'Floor', 'ar': 'الطابق'},
    'licensePlate': {'en': 'License Plate', 'ar': 'رقم اللوحة'},
    'code': {'en': 'Code', 'ar': 'الكود'},
    'start': {'en': 'Start', 'ar': 'البداية'},
    'end': {'en': 'End', 'ar': 'النهاية'},
    'myProfile': {'en': 'My Profile', 'ar': 'حسابي'},
    'myBookings': {'en': 'My Bookings', 'ar': 'حجوزاتي'},
    'bookingHistory': {'en': 'View booking history & active reservations', 'ar': 'عرض سجل الحجوزات والحجوزات النشطة'},
    'accountInfo': {'en': 'Account Info', 'ar': 'معلومات الحساب'},
    'logoutConfirm': {'en': 'Are you sure you want to logout?', 'ar': 'هل أنت متأكد من تسجيل الخروج؟'},
    'cancel': {'en': 'Cancel', 'ar': 'إلغاء'},
    'confirm': {'en': 'Confirm', 'ar': 'تأكيد'},
    'edit': {'en': 'Edit', 'ar': 'تعديل'},
    'done': {'en': 'Done', 'ar': 'تم'},
    'keep': {'en': 'Keep', 'ar': 'إبقاء'},
    'cancelIt': {'en': 'Cancel It', 'ar': 'ألغيه'},
    'bookingSummary': {'en': 'Booking Summary', 'ar': 'ملخص الحجز'},
    'slotNumber': {'en': 'Slot Number', 'ar': 'رقم المكان'},
    'date': {'en': 'Date', 'ar': 'التاريخ'},
    'time': {'en': 'Time', 'ar': 'الوقت'},
    'duration': {'en': 'Duration', 'ar': 'المدة'},
    'pickDate': {'en': 'Pick the date', 'ar': 'اختر التاريخ'},
    'pickTime': {'en': 'Pick the time you would arrive', 'ar': 'اختر وقت وصولك'},
    'licensePlateNumber': {'en': 'License Plate Number', 'ar': 'رقم لوحة السيارة'},
    'continueBtn': {'en': 'Continue', 'ar': 'متابعة'},
    'fillAllDetails': {'en': 'Fill All Details', 'ar': 'أكمل جميع البيانات'},
    'noBookingsYet': {'en': 'No bookings yet', 'ar': 'لا توجد حجوزات بعد'},
    'historyAppearHere': {'en': 'Your reservation history will appear here', 'ar': 'سجل حجوزاتك سيظهر هنا'},
    'activeReservations': {'en': 'Active Reservations', 'ar': 'الحجوزات النشطة'},
    'pastReservations': {'en': 'Past Reservations', 'ar': 'الحجوزات السابقة'},
    'active': {'en': 'Active', 'ar': 'نشط'},
    'expired': {'en': 'Expired', 'ar': 'منتهي'},
    'cancelled': {'en': 'Cancelled', 'ar': 'ملغي'},
    'reservationCancelled': {'en': 'Reservation cancelled!', 'ar': 'تم إلغاء الحجز!'},
    'failedToCancel': {'en': 'Failed to cancel', 'ar': 'فشل الإلغاء'},
    'cancelReservationQ': {'en': 'Cancel Reservation?', 'ar': 'إلغاء الحجز؟'},
    'bookingConfirmed': {'en': 'Booking confirmed', 'ar': 'تم تأكيد الحجز'},
    'bookingFailed': {'en': 'Booking failed!', 'ar': 'فشل الحجز!'},
    'language': {'en': 'العربية', 'ar': 'English'},
    'darkMode': {'en': 'Dark Mode', 'ar': 'الوضع الليلي'},
    'settings': {'en': 'Settings', 'ar': 'الإعدادات'},
    'available': {'en': 'Available', 'ar': 'متاح'},
    'occupied': {'en': 'Occupied', 'ar': 'مشغول'},
    'reserved': {'en': 'Reserved', 'ar': 'محجوز'},
    'selected': {'en': 'Selected', 'ar': 'محدد'},
    'extendBy': {'en': 'Extend by', 'ar': 'تمديد بمقدار'},
    'minutes': {'en': 'minutes', 'ar': 'دقيقة'},
    'extended': {'en': 'Reservation extended!', 'ar': 'تم تمديد الحجز!'},
    'failedToExtend': {'en': 'Failed to extend', 'ar': 'فشل التمديد'},
    'reservationEndingSoon': {'en': 'Your parking reservation is ending soon!', 'ar': 'حجز الموقف ينتهي قريباً!'},
    'minutesLeft': {'en': 'minutes left', 'ar': 'دقيقة متبقية'},
    'chosenSlotDetails': {'en': 'Your chosen slot details :', 'ar': 'تفاصيل المكان المختار :'},
  };

  static String get(String key, String lang) {
    return _strings[key]?[lang] ?? _strings[key]?['en'] ?? key;
  }
}
