# Generated by Django 6.0.3 on 2026-04-12 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='car_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='last_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.camera'),
        ),
    ]
