# Generated by Django 6.0.3 on 2026-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='floor',
            field=models.IntegerField(default=1),
        ),
    ]
