# Generated by Django 6.0.3 on 2026-04-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehiclelog_car_embedding_vehiclelog_last_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('slot_number', 'floor')},
        ),
    ]
