# Generated by Django 6.0.3 on 2026-03-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingslot_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingslot',
            options={'ordering': ['floor', 'row', 'col']},
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='col',
            field=models.PositiveIntegerField(default=0, help_text='Grid column index for navigation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='row',
            field=models.PositiveIntegerField(default=0, help_text='Grid row index for navigation'),
            preserve_default=False,
        ),
    ]
